### ISSUE TITLE
Install requirements

### ISSUE THREAD

**Issue by arnaldorusso** [njwilson23/narwhal#6]
Hi,

Maybe you should address an information that karta should be installed with their requirements.txt as well. While installing following your stpes, it does not install `shapefiles`

while running `runtests.py`
    
    ImportError: No module named shapefile

I have cloned `karta` and install their requirements and compiled again.
Now it pass:

    ...............................................
    ----------------------------------------------------------------------
    Ran 47 tests in 0.355s
    
    OK

Is there any possible way to assert requirements.txt from other packages?

Cheers,
Arnaldo.

**Comment by njwilson23** [comment]
I think this should be fixed now, so closing.
